sudo: required
services:
  - docker

before_install:
  - docker build -t phoax/testk8s -f ./client/Dockerfile.dev ./client

script:
  - docker run USERNAME/react-test npm test -- --coverage

after_success:
  - docker build -t phoax/testk8s ./client
  - docker build -t phoax/testk8s ./nginx
  - docker build -t phoax/testk8s ./server
  - docker build -t phoax/testk8s ./worker
